modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Dat-Developer-Mods/create-war/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="datdeveloper.com"
logoFile="create_war.png"
#credits="Thanks for this example mod goes to Java"
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="create"
   mandatory=true
   versionRange="[0.5.1.c,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="cc-tweaked"
   mandatory=false
   versionRange="[1.107.0,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.${mod_id}]]
   modId="jei"
   mandatory=false
   versionRange="[15.2.0.27.0,)"
   ordering="AFTER"
   side="BOTH"
